apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: sfs-pv