apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:latest
        args: [ "start-dev" ]
        volumeMounts:
        - name: keycloak-storage
          mountPath: /opt/keycloak/data/
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        ports:
        - containerPort: 8080
      volumes:
      - name: keycloak-storage
        persistentVolumeClaim:
          claimName: keycloak-data-pvc
