apiVersion: v1
kind: Service
metadata:
  name: gui-service
  labels:
    app: gui
spec:
  type: ClusterIP
  selector:
    app: gui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  labels:
    app: gui
spec:
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
        - name: gui
          image: vlassisioa/distributed-mapreduce:gui
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http